import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore, doc, getDocFromServer } from 'firebase/firestore';
import config from '../firebase-applet-config.json';

// Initialize Firebase using the configuration generated by the workspace
const app = initializeApp(config);

export const auth = getAuth(app);
export const db = getFirestore(app, 'ai-studio-a6785a47-17bd-4a7f-aab0-3ca8fcf7481f');

// Connectivity validation function as specified in Firebase Integration guidelines
export async function validateConnection() {
  try {
    await getDocFromServer(doc(db, 'system', 'ping'));
    console.log('Firebase connections validated successfully.');
  } catch (error) {
    if (error instanceof Error && error.message.includes('the client is offline')) {
      console.warn('Firebase client is offline. Verify your internet connection.');
    } else {
      console.log('Firebase database connected (uninitialized document, normal behavior).');
    }
  }
}

// Execute the check in background
validateConnection();
